name: Build and Push Docker Image

me:
Build a
d Push Docker I main o
:
  push:

   branches: [ main 

    paths:
      
 'Dockerfile'
      - 
index.js'
     
- 'package.json main l
_request:
    branch

: [ m
in ]
  w
rkflow_dispatubuntu-latest
uild:
    runs-o
: ubuntu-latest
read
ermissions:
    write

nts: read

     packages:Checkout repository
     - name: Cactions/checkout@v4

      uses: acLog in to GitHub Container Registry
 in to GitHub docker/login-action@v3
    uses: doc
er/login-action@v3
 ghcr.io
ith:
          regis$ry github.actor   
   username: ${{ git$ub secrets.GITHUB_TOKEN ss

rd: ${{ secretSet up Docker Buildx
    - name: Sedocker/setup-buildx-action@v3

: docker/setupBuild and push Docker image
ame: Build anddocker/build-push-action@v5
ses: docker/b
ild-push-action@v5
 
      with:
        
 context: .
         linux/amd64,linux/arm64
atforms: linux/am
64,linux/arm64
          tags: |
            ghcr.io/${{ git
ub.repository_owner
}}/ws:latest
          labels: |
            org.opencontainers.image.source=https://gi
hub.com/${{ github.repository }}
            org.opencontain
rs.image.description=HTTP Server
            org.
pencontainers.image.litype=gha
            cache-frtype=gha,mode=max
            L7XHmx8pzrsq@ep-dry-band-a1delbk5.ap-southeast-1.pg.koyeb.app
            production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] =%>
